version: '3.3'
networks:
   back-tier:
     driver: bridge
   front-tier:
     driver: bridge
   admin-tier:
     driver: bridge

services:
   front-web:
       image: nginx:latest
       ports:
       - '80'
       volumes:
         - ./nginx:/etc/nginx/conf.d
         - ./nginx.conf:/etc/nginx/nginx.conf
         - ./logs/nginx:/var/log/nginx
         - ./wordpress:/var/www/html
       depends_on:
         - systm-wps
       restart: always
       networks:
         - back-tier
         - front-tier

   datab-wps:
     image: mariadb
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: example
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     volumes:
       - ./db_data:/var/lib/mysql
     networks:
       - back-tier

   front-adm:
     image: adminer
     restart: always
     depends_on:
       - datab-wps
     ports:
       - 8080
     networks:
       - back-tier
       - admin-tier
              
   systm-wps:
     image: wordpress:php7.2-fpm
     ports:
       - 9000
     networks:
       - back-tier
     depends_on:
       - datab-wps
     links:
       - datab-wps
     restart: always
     volumes:
       - ./wordpress:/var/www/html
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

   loadb-web:
     image: dockercloud/haproxy
     ports:
       - 80:80
       - 443:443
     links:
       - front-web
     networks:
       - front-tier
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock

   loadb-adm:
    image: dockercloud/haproxy
    ports:
      - 8080:80
    links:
      - front-adm
    networks:
      - admin-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
