version: '3.3'
networks:
   back-net:
     driver: bridge
   front-net:
     driver: bridge
   admin-net:
     driver: bridge

services:
   datab-wps:
     image: mariadb
     restart: always
     ports:
       - 3306
     networks:
       - back-net
     volumes:
       - ./db_data:/var/lib/mysql 
     environment:
       MYSQL_ROOT_PASSWORD: example
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
      
   
   systm-wps:
     image: wordpress:php7.2-fpm
     restart: always
     ports:
       - 9000
     depends_on:
       - datab-wps
     links:
       - datab-wps
     networks:
       - back-net
     volumes:
       - ./wordpress:/var/www/html
     environment:
       WORDPRESS_DB_HOST: datab-wps:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
   
   front-adm:
     image: adminer
     restart: always
     ports:
       - 8080
     depends_on:
       - datab-wps
     networks:
       - back-net
       - admin-net
   
   front-web:
     image: nginx:latest
     restart: always
     ports:
     - '80'
     depends_on:
       - systm-wps
     networks:
       - back-net
       - front-net
     volumes:
       - ./nginx:/etc/nginx/conf.d
       - ./nginx.conf:/etc/nginx/nginx.conf
       - ./logs/nginx:/var/log/nginx
       - ./wordpress:/var/www/html

   loadb-web:
     image: dockercloud/haproxy
     restart: always
     ports:
       - 80:80
       - 443:443
     depends_on:
       - front-web
     links:
       - front-web
     networks:
       - front-net
     
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock

   loadb-adm:
     image: dockercloud/haproxy
     restart: always
     ports:
       - 8080:80
     depends_on:
       - front-adm 
     links:
       - front-adm
     networks:
       - admin-net
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
